<?xml version="1.0" encoding="UTF-8"?><testrun duration="20" footerText="Generated by IntelliJ IDEA on 8/3/23 20:13" name="DoubleEndedQueueExceptionTest">
    <count name="total" value="2"/>
    <count name="passed" value="2"/>
    <config nameIsGenerated="true" configId="JUnit" name="DoubleEndedQueueExceptionTest">
        <module name="ColaDoble"/>
        <extension name="coverage">
            <pattern>
                <option name="PATTERN" value="org.mps.deque.*"/>
                <option name="ENABLED" value="true"/>
            </pattern>
        </extension>
        <option name="PACKAGE_NAME" value="org.mps.deque"/>
        <option name="MAIN_CLASS_NAME" value="org.mps.deque.DoubleEndedQueueExceptionTest"/>
        <option name="TEST_OBJECT" value="class"/>
        <method v="2">
            <option name="Make" enabled="true"/>
        </method>
    </config>
    <root name="Test cases when creating an exception" comment="org.mps.deque" location="java:suite://org.mps.deque.DoubleEndedQueueExceptionTest">
        <output type="stdout">"C:\Program Files\Java\jdk-17.0.1\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\lib\idea_rt.jar=63740:C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\nurir\.m2\repository\org\junit\platform\junit-platform-launcher\1.9.2\junit-platform-launcher-1.9.2.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\plugins\junit\lib\junit5-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\plugins\junit\lib\junit-rt.jar;D:\Documentos\3Carrera\Mantenimiento_y_pruebas\ColaDoble\target\test-classes;D:\Documentos\3Carrera\Mantenimiento_y_pruebas\ColaDoble\target\classes;C:\Users\nurir\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.9.2\junit-jupiter-engine-5.9.2.jar;C:\Users\nurir\.m2\repository\org\junit\platform\junit-platform-engine\1.9.2\junit-platform-engine-1.9.2.jar;C:\Users\nurir\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\nurir\.m2\repository\org\junit\platform\junit-platform-commons\1.9.2\junit-platform-commons-1.9.2.jar;C:\Users\nurir\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.9.2\junit-jupiter-api-5.9.2.jar;C:\Users\nurir\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\nurir\.m2\repository\org\junit\jupiter\junit-jupiter-params\5.9.2\junit-jupiter-params-5.9.2.jar" com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit5 org.mps.deque.DoubleEndedQueueExceptionTest
Process finished with exit code 0
</output>
    </root>
    <suite duration="20" locationUrl="java:suite://org.mps.deque.DoubleEndedQueueExceptionTest$WhenCreatingAnException" name="when creating an exception" status="passed">
        <test duration="19" locationUrl="java:test://org.mps.deque.DoubleEndedQueueExceptionTest$WhenCreatingAnException/creatingADoubleEndedQueueExceptionMessageIsCorrect" name="message is correct" metainfo="" status="passed"/>
        <test duration="1" locationUrl="java:test://org.mps.deque.DoubleEndedQueueExceptionTest$WhenCreatingAnException/creatingADoubleEndedQueueException" name="object is created" metainfo="" status="passed"/>
    </suite>
</testrun>
